baseURL = "https://sanjay-saxena.io/"
languageCode = "en-us"
title = "sanjay-saxena.io"
theme = "hyde"
copyright = "Sanjay Saxena"

[Author]
	name = "Sanjay Saxena"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "by Sanjay Saxena"
	github = "https://github.com/sanjay-saxena"
	disqus = "sanjay-saxena-github-io"
    disqusShortname = "sanjay-saxena-github-io"
    themeColor = "theme-base-0d"

